spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bbs?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 12345678
  mvc:
    static-path-pattern: /static/**
  application:
    name: bbs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 80
  servlet:
    context-path: /